name: Run OpenFDA API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: |
          newman run OpenFDA_Postman_Collection.json \
          -e OpenFDA_Postman_Environment.json \
          --reporters cli,junit \
          --reporter-junit-export results.xml

      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: newman-results
          path: results.xml

          
